### ISSUE TITLE
Provide de-Lomboked code

### ISSUE THREAD

**Issue by MiniDigger** [keir-nellyer/PluginMessageAPI-Plus-LEGACY#1]
You should only push code without the Lombok annotations (real java code).
Not everyone is using Lombok ;D

**Comment by keir-nellyer** [comment]
I did intend to release this on a Maven dependency and then users could include it in their jar and then that wouldn't be a problem however I currently don't have a dedicated server of any sort so yeah I'll try and de-lombok it soon.
