### ISSUE TITLE
Support Packets which do not have the same Class Path

### ISSUE THREAD

**Issue by geNAZt** [keir-nellyer/PluginMessageAPI-Plus-LEGACY#2]
Currently i am forced to have the Messages in Bukkit and in BungeeCord in the same Classpath. Maybe that could change so i can use different Classpaths

**Comment by keir-nellyer** [comment]
I'm not exactly sure what you mean. If you want to access packets from another plugin then it should work as Bukkit adds all plugins into the same class loader. Please correct me if I am wrong

**Comment by geNAZt** [comment]
Well for example:

In the Bungeecord Part i have this Class:
net.cubespace.cloudchat.module.ChatModule.FactionMessage

and in the Bukkit Part i have the "same" Class under this Classpath:
net.cubespace.cloudchatbukkit.Messages.FactionMessage

It will never work since they need to have the same Classpath.

**Comment by keir-nellyer** [comment]
Ah, I see. What's the issue with that? If it didn't work the way it did then you wouldn't be able to register 2 packets with the same packet name. This is intended to work with a structure possibly like this

net.cubespace.cloudchat.common.packets -> Packet package
net.cubespace.cloudchat.bukkit -> Bukkit package
net.cubespace.cloudchat.bungee -> BungeeCord package

I do it similarly to the way Bukkit and BungeeCord do their code. Have multiple modules and some are shared. For example Bukkit is copied into the CraftBukkit jar. You can do this with Maven plugins, I would tell you how to do it but my pc chose to reset itself today and so I don't have my IDE setup yet.

**Comment by geNAZt** [comment]
Maybe there should be a Way to set identifier to Packets. Maybe if you register them. Like

registerPacket("AffixMessage", AffixMessage.class);

and if you try to register a Packet twice give a DuplicatePacketRegistrationException or something

**Comment by keir-nellyer** [comment]
Hmm, why don't you create 3 maven modules (or refer to the as sub-projects if it helps). They would be named Common, Bukkit, BungeeCord. Common would have you're packets and I shouldn't need to explain the other 2. The Bukkit and BungeeCord modules would depend on the Common module. And then just add this to you're Bukkit and BungeeCord pom.xml's http://pastebin.com/vUpDgM73

The reason I'm not too keen on what you suggest is it may be confusing to some people and I just see it as something that doesn't need to be added as there are easy ways around it that would also make it easier for you (only having to write the Packet class once as it gets copied from the Common module)

Hope this helps
