### ISSUE TITLE
NPE in PluginMessageListener

### ISSUE THREAD

**Issue by geNAZt** [keir-nellyer/PluginMessageAPI-Plus-LEGACY#5]
I randomly get NPE reported from the Users of my Plugin. I am near 100% sure that the NPE comes from your API.

The report they give me: http://pastebin.com/rqJHHeVu

The receiver Listener: https://github.com/geNAZt/CloudChat/blob/master/src/main/java/net/cubespace/CloudChat/Module/PlayerManager/Listener/PluginMessageListener.java

The sender: https://github.com/geNAZt/CloudChatBukkit/blob/master/src/main/java/net/cubespace/CloudChatBukkit/Listener/PlayerJoin.java

So I think either the whole Message or getSender() is null.

**Comment by regaw-leinad** [comment]
Unfortunately, that NPE is in your code, and you've changed it since the logs were pulled, so the line numbers are off. Not very easy to visually debug that.  Also, you made a large wrapper for the API, so there's a very good possibility that the error resides in that. The only real error I'm seeing is an InvocationTargetException when it tries to call your listener methods. Is it possible you shaded in the wrong version of the packets to one of the packages?

**Comment by geNAZt** [comment]
If i would have shaded in the wrong Versions of the Messages i would get that error more often. I get that error in maybe 10 out of 150k Messages

**Comment by geNAZt** [comment]
But it seems that the Error is in BungeeCord. As i see in the Log he has more Plugins installed from me which use the basic Plugin Channel API from BungeeCord. And even the ones are failing because  BungeeCord does not seem to find the ProxiedPlayer. I need to investigate more on that issue

**Comment by keir-nellyer** [comment]
The issue is definetely nothing to do with my code, it may seem like that due to the "InvocationTargetException" but all that means is that I called a constructor via reflection and that constructor threw an error. The real error is below, the "NullPointerException"

**Comment by regaw-leinad** [comment]
Found one of your problems... In your own code.

```
ProxiedPlayer player = NicknameParser.getPlayer(plugin, args[0]);
if (player == null) {
        MessageBuilder messageBuilder = new MessageBuilder();
        messageBuilder.setText(FontFormat.translateString(messages.Command_Unmute_OfflinePlayer.replace("%player", player.getName()))).send(sender);
            return;
        }
```

This is in net.cubespace.CloudChat.Module.Mute.Command line 80.
Notice how you make sure the player is null before doing the unmute?

**Comment by keir-nellyer** [comment]
I imagine you meant to do != there?

**Comment by geNAZt** [comment]
Yes thanks for pointing that out. But the code has nothing todo with the plugin crash

**Comment by geNAZt** [comment]
And I looked in that code and if work like intended. I opened a bungeecord issue to get that done

**Comment by regaw-leinad** [comment]
Umm I followed one of the logs stack traces right to that.. so yes, that does affect the plugin.

**Comment by keir-nellyer** [comment]
You're incorrect if statement is causing that code to ONLY be run if the player is null. This results in any time that block of code does run, it will throw a NullPointerException
